/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPACE = 4;
  /** RegularExpression Id. */
  int XOR = 5;
  /** RegularExpression Id. */
  int NOT = 6;
  /** RegularExpression Id. */
  int IN = 7;
  /** RegularExpression Id. */
  int DISTINCT = 8;
  /** RegularExpression Id. */
  int STARTS = 9;
  /** RegularExpression Id. */
  int ENDS = 10;
  /** RegularExpression Id. */
  int WITH = 11;
  /** RegularExpression Id. */
  int CONTAINS = 12;
  /** RegularExpression Id. */
  int IS = 13;
  /** RegularExpression Id. */
  int NULL = 14;
  /** RegularExpression Id. */
  int LIKE = 15;
  /** RegularExpression Id. */
  int FROM = 16;
  /** RegularExpression Id. */
  int EOL = 17;
  /** RegularExpression Id. */
  int PLUS = 18;
  /** RegularExpression Id. */
  int MINUS = 19;
  /** RegularExpression Id. */
  int MULTIPLY = 20;
  /** RegularExpression Id. */
  int DIVIDE = 21;
  /** RegularExpression Id. */
  int EXP = 22;
  /** RegularExpression Id. */
  int MOD = 23;
  /** RegularExpression Id. */
  int STARTLIST = 24;
  /** RegularExpression Id. */
  int ENDLIST = 25;
  /** RegularExpression Id. */
  int SELECT = 26;
  /** RegularExpression Id. */
  int MATCH = 27;
  /** RegularExpression Id. */
  int WHERE = 28;
  /** RegularExpression Id. */
  int JOIN = 29;
  /** RegularExpression Id. */
  int PROJECT = 30;
  /** RegularExpression Id. */
  int STARTSWITH = 31;
  /** RegularExpression Id. */
  int ENDSWITH = 32;
  /** RegularExpression Id. */
  int CONDITIONALOPERATOR = 33;
  /** RegularExpression Id. */
  int LOGICALOPERATOR = 34;
  /** RegularExpression Id. */
  int NUMERIC = 35;
  /** RegularExpression Id. */
  int IDENTIFIER = 36;
  /** RegularExpression Id. */
  int LETTER = 37;
  /** RegularExpression Id. */
  int DIGIT = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\f\"",
    "\" \"",
    "\"XOR\"",
    "\"NOT\"",
    "\"IN\"",
    "\"DISTINCT\"",
    "\"STARTS\"",
    "\"ENDS\"",
    "\"WITH\"",
    "\"CONTAINS\"",
    "\"IS\"",
    "\"NULL\"",
    "\"LIKE\"",
    "\"FROM\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"%\"",
    "\"[\"",
    "\"]\"",
    "\"SELECT\"",
    "\"MATCH\"",
    "\"WHERE\"",
    "\"JOIN\"",
    "\"PROJECT\"",
    "<STARTSWITH>",
    "<ENDSWITH>",
    "<CONDITIONALOPERATOR>",
    "<LOGICALOPERATOR>",
    "<NUMERIC>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\".\"",
  };

}
